# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0296031e0e8fcd3ce683408dc353648e9f034ac8a383e8efadeb043f57554a1bd56ea6804cd5366f797d62ebeabbbb0145d47f31e80b5fbe75bd393112acff01

test:
  secret_key_base: 2c6147c4d1232c48a17021093a80e614513b9f7bbb4e841ab3b7a5487375d0d3fb45df4454ccd5a0ad0183623f7e5651149c3644b44300dd7abf959193a82884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
